all:
  children:
    drupal_servers:
      hosts:
        web1:
          ansible_host: 44.222.219.79
        web2:
          ansible_host: 184.73.84.159
      vars:
        ansible_user: ec2-user
        ansible_ssh_private_key_file: ~/.ssh/drupal-key
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
